# 2025-01-01  William A. Hudson

# Run all test suites.

PATH = /usr/bin:/bin

SHELL = /bin/sh

test:
	cd t_nscc             && make test
	cd t_nsc              && make test

clean:
	cd t_nscc             && make clean
	cd t_nsc              && make clean

