#! /bin/bash

# Run Noir camera with rpicam-still.

export DISPLAY=:0

set -x

vcgencmd measure_temp

rpicam-still -t 0  --hflip --vflip --gain=1.0 --awbgains=1.0,0.1  ${@}

vcgencmd measure_temp


# Output File Options:
#    -o, --output=FILE
#		Name of the output file.
#		Can use network address, udp://  or tcp://
#		String "%d" replaced with file open count (see --framestart).

# Control options:

#    -t, --timeout=N_ms
#		Preview window delay (in milliseconds), 0= indefinitely.

#    -k, --keypress
#		Keypress mode to capture image.
#		<enter>  = capture image
#		<x>      = quit without capturing
#		Repeat <enter> to capture another, overwrite file unless %d.
#		After first <enter>, get message "Still capture image received"
#		suggesting shutter is closed again.

#    --shutter=N_us
#		Set the exposure time in microseconds.
#		670.74 s  max HQ camera
#		112 s     max Camera Module 3
#		11.76 s   max Camera Module v2

#    --gain=N
#		Sets the combined analogue and digital gains.
#		[Disables AEC/AGC.]
#		AnalogueGain : [1.000000 .. 22.260870]

#    --awbgains=Nred,Nblue
#		Set fixed colour gains.  [are w.r.t. green?]
#		Disable Automatic White Balance (AWB) algorithm.
#		Note:  Setting a gain to 0.0 may cause it to be ignored.

#    --denoise={auto (default), off, ..}

#    -f, --fullscreen
#		Force preview window to use full screen.
#		Use <Alt><Esc> to lower the preview window.
#		The preview window is NOT an X11 window, but is under window
#		manager control to some degree.

