# 2022-03-10  William A. Hudson

# Run all test suites.

PATH = /usr/bin:/bin

SHELL = /bin/sh

test:
	cd t_dNcOsc           && make test
	cd t_dNcRamp          && make test
	cd t_dNcRamp_a        && make test
	cd t_dNcScaler        && make test
	cd t_dNcWave          && make test
	cd t_dac_mcp4822      && make test
	cd t_extShift         && make test
	cd t_uspi_mcp4822x    && make test

clean:
	cd t_dNcOsc           && make clean
	cd t_dNcRamp          && make clean
	cd t_dNcRamp_a        && make clean
	cd t_dNcScaler        && make clean
	cd t_dNcWave          && make clean
	cd t_dac_mcp4822      && make clean
	cd t_extShift         && make clean
	cd t_uspi_mcp4822x    && make clean

