#! /usr/bin/perl -w
# 2022-10-19  William A. Hudson

# Re-format DAQ data table to fixed-point numbers.
# Input:   |   1.9477678e+00   3.2489139e+00  -4.1134664e-01  -6.8250492e-02
# Output:  | 1.94777  3.24891 -0.41135 -0.06825

# usage:  reformat_daq < k6_set_10_daq.txt

while ( <> ) {
    my @data = split( ' ', $_ );

    printf( "%8.5f %8.5f %8.5f %8.5f\n", @data );
	# assume exactly 4 values with resolution to 0.01 mV
}

