#! /usr/bin/perl -w
# 2024-02-22  William A. Hudson

# Re-format Galvo/DAQ data table to fixed-point numbers.
# Input:   |   1.9477678e+00   3.2489139e+00  -4.1134664e-01
# Output:  | 1.94777  3.24891 -0.41135

# usage:  reformat_galvo < k6_set_10_daq.txt

while ( <> ) {
    my @data = split( ' ', $_ );

    printf( "%8.5f %8.5f %8.5f\n", @data );
	# assume exactly 3 values with resolution to 0.01 mV
}

