#! /bin/bash
# 2024-07-07  William A. Hudson

# Run 'Command' (i.e. to_pgm) on a list of files.

# usage:  to_pgmFile  Command < list
# usage:  ls *.dat | to_pgmFile  Command
# usage:  ls *.dat.gz | to_pgmFile  "gunzip | Command"
#
#    Command = command executed with redirected stdin, stdout and stderr.
#        Can be a pipeline.

#set -x

while read  ifile
do
    if [[ ${ifile} =~ " " ]]		# has a <space>
    then
	echo "Error:  whitespace in list:  ${ifile}" >&2
	exit 1
    fi

    base=${ifile%%\.*}		# file base name, remove longest .suffix

    ofile=${base}.pgm
    efile=${base}.pgmerr

    cmd="<'${ifile}'  ${@}  >'${base}.pgm'  2>'${base}.pgmerr'"

    echo "+ ${cmd}"

    eval ${cmd}

done

